version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo apt-get install pandoc  
      - run: sudo pip install tox
      - run: tox
      - run: ls -la docs
      - persist_to_workspace:
          root: docs
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs
      - run: mkdir -p website/docs && mv docs/html website/docs/
      - run:
          name: Disable jekyll builds
          command: touch docs/html/.nojekyll
      - run: mkdir -p docs/html/.circleci
      - run: cp .circleci/config.yml docs/html/.circleci/config.yml
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "$(git log --format=%ae -n 1)"
            git config user.name "$(git log --format=%an -n 1)"
      - add_ssh_keys:
          fingerprints:
            - "80:30:82:3d:5f:0b:19:f0:2c:27:f7:3b:d8:a2:a0:c0"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages -b website --dotfiles --message "$(git log --format=%B -n 1)" --dist website
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: docs
      - docs-deploy:
          requires:
            - test
          filters:
            branches:
              only: main
